config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :profiles, only: [:edit, :update]
  resources :orders, except: [:new, :destroy, :edit] do
    get 'accept'
  end
  resources :products, only: [:index]

  root to: 'products#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, Order, user_id: user.id
    can :read, Product

    if user.is_a? AdminUser
      can :manage, Product
      can :manage, User
      can :manage, Order
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product_attr
  belongs_to :order

  validates :quantity, numericality: { only_integer: true, greater_than: 0 }

  after_destroy :free_products

  private

  def free_products
    current_amount = product_attr.amount
    new_amount = current_amount + quantity
    product_attr.update!(amount: new_amount)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  accepts_nested_attributes_for :line_items, reject_if: proc { |attrs| attrs['quantity'].to_i.zero? }

  enum status: [:not_confirmed, :confirmed, :declined, :pending, :done]

  after_update :check_if_decline

  validates :status, presence: true

  STATUSES = [['Подтвержден', :confirmed], ['В обработке', :pending], ['Отклонен', :declined],
              ['Выполнен', :done]].freeze

  def calculate_total_price
    self.total_price = line_items.inject(0) { |mem, elem| mem + elem.product_attr.price * elem.quantity }
  end

  def check_amounts
    line_items.each do |l_i|
      return false if l_i.quantity > l_i.product_attr.amount
    end
    true
  end

  def lock_products
    line_items.each do |line_item|
      line_item.product_attr.update(amount: line_item.product_attr.amount - line_item.quantity)
    end
  end

  def confirmed!
    update(status: :confirmed)
    if user.alert
      OrderNotifierMailer.new_order_notify(self).deliver_now
      SMSSender.send_message(user, self)
    end
  end

  def translate_status
    case status
    when 'confirmed'
      'Подтвержден'
    when 'pending'
      'В обработке'
    when 'done'
      'Выполнен'
    when 'declined'
      'Откланен'
    when 'not_confirmed'
      'Не подтвержден'
    end
  end

  private

  def check_if_decline
    if status == 'declined'
      line_items.each do |l_i|
        current_amount = l_i.product_attr.amount
        new_amount = current_amount + l_i.quantity
        l_i.product_attr.update!(amount: new_amount)
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_attrs, -> { includes :size }
  has_many :sizes, through: :product_attrs

  accepts_nested_attributes_for :product_attrs, reject_if: :all_blank

  validates :name, uniqueness: true, presence: true
end

app/models/product_attr.rb
class ProductAttr < ApplicationRecord
  belongs_to :product
  belongs_to :size
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :product_attrs
  has_many :products, through: :product_attrs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone_number, length: { is: 9 }, presence: true, uniqueness: true, numericality: { only_integer: true }
  validates :organization, presence: true, length: { minimum: 3 }

  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |_exception|
    flash[:error] = "Отказано в доступе"
    redirect_to root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:organization, :phone_number]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @orders = current_user.orders.where.not(status: 0).order(created_at: :desc)
  end

  def create
    if @order.line_items.empty?
      flash[:alert] = "Не выбрана ни одна из позиций"
      redirect_to :back
    else
      if @order.check_amounts
        @order.calculate_total_price
        @order.user_id = current_user.id
        if @order.save
        else
          flash[:error] = @order.errors.full_messages.join('. ')
          redirect_to :back
        end
      else
        flash[:alert] = "Превышено количество одной из позиций"
        redirect_to :back
      end
    end
  end

  def show; end

  def update
    @order.lock_products
    @order.confirmed!
    flash[:notice] = 'Заказ успешно создан и принят на обработку'
    redirect_to root_path
  end

  def accept
    @order = Order.find(params[:order_id])
    @order.pending!
  end

  private

  def order_params
    params.require(:order).permit(line_items_attributes: [:product_attr_id, :quantity])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @products = @products.select { |p| p.product_attrs.first.size.value != '-'.freeze }
                         .sort { |a, b| a.product_attrs.min_by(&:price).price <=> b.product_attrs.min_by(&:price).price } +
                @products.select { |p| p.product_attrs.first.size.value == '-'.freeze }
    @products = ProductDecorator.decorate_collection(@products)
    @order = Order.new
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if user_params[:password].present?
      if @user.update(user_params)
        sign_in @user, bypass: true
        flash[:notice] = "Профиль был успешно обновлен"
        redirect_to :back
      else
        flash[:alert] = @user.errors.full_messages.join('. ')
        redirect_to :back
      end
    else
      if @user.update_without_password(user_params)
        flash[:notice] = "Профиль был успешно обновлен"
        redirect_to :back
      else
        flash[:alert] = @user.errors.full_messages.join('. ')
        redirect_to :back
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :organization, :phone_number, :password, :password_confirmation)
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.join('. ')

    html = <<-HTML
      <div class="alert alert-warning" role="alert">
        <button aria-label="Close" class="close" data-dismiss="alert" type="button">
          <span aria-hidden="true">&times;</span>
        </button>
        #{messages}
      </div>
    HTML

    html.html_safe
  end
end

app/views/flashes/_alert.html.slim
.alert.alert-warning role='alert'
  button type="button" class="close" data-dismiss="alert" aria-label="Close"
    span aria-hidden="true" &times;
  = message

app/views/flashes/_erorr.html.slim
.alert.alert-warning role='alert'
  button type="button" class="close" data-dismiss="alert" aria-label="Close"
    span aria-hidden="true" &times;
  = message

app/views/flashes/_error.html.slim
.alert.alert-danger role='alert'
  button type="button" class="close" data-dismiss="alert" aria-label="Close"
    span aria-hidden="true" &times;
  = message

app/views/flashes/_notice.html.slim
.alert.alert-success role='alert'
  button type="button" class="close" data-dismiss="alert" aria-label="Close"
    span aria-hidden="true" &times;
  = message

app/views/layouts/application.html.slim
doctype html
html
  head
    title StoreMonitor
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  body
    .container
      .row
        nav.navbar.navbar-default style="margin-top: 5px"
          .container-fluid
            .navbar-header
              = link_to root_path, class: 'navbar-brand', style: 'padding-top: 5px;' do
                = image_tag 'logo.png'
              span.phone +375 29 1750130
            ul.nav.navbar-nav.navbar-right
              - if user_signed_in?
                li
                  = link_to 'Мои заказы', orders_path
                li
                  = link_to 'Профиль', edit_profile_path(current_user.id)
                li
                  = link_to 'Выход', destroy_user_session_path, method: :delete
              - else
                li
                  = link_to 'Регистрация', new_user_registration_path
                li
                  = link_to 'Вход', new_user_session_path
        - if flash.present?
          - flash.each do |name, msg|
            - if name == "notice"
              = render partial: 'flashes/notice', locals: {message: msg}
            - elsif name == "alert"
              = render partial: 'flashes/alert', locals: {message: msg}
            - elsif name == "error"
              = render partial: 'flashes/error', locals: {message: msg}
      = yield

app/views/orders/_order.html.slim
tr
  td.align-middle
    = order.created_at.strftime("%H:%M  %d-%m-%y")
  td.align-middle
    = number_to_currency(order.total_price, delimiter: ' ', precision: 0, format: '%n')
  td.align-middle
    = order.translate_status
  td.text-center
    = link_to 'Подробнее', order_path(order.id), class: 'btn btn-info'

app/views/orders/_order_row.html.slim
tr
  td.align-middle.col-md-4
    = line_item.product_attr.product.name
  td.align-middle.col-md-2
    = line_item.product_attr.size.value
  td.align-middle.col-md-2
    = number_to_currency(line_item.product_attr.price, delimiter: ' ', precision: 0, format: '%n')
  td.align-middle.col-md-2
    = line_item.quantity
  td.align-middle.col-md-2
    = number_to_currency(line_item.quantity * line_item.product_attr.price, delimiter: ' ', precision: 0, format: '%n')

app/views/orders/accept.html.slim
.row
  .col-md-12
    h1.text-center
      | Заказ успешно был переведен в статус 'В обработке'

app/views/orders/create.html.slim
.row
  = form_for @order do |f|
    = f.hidden_field :id
    .col-md-10.col-md-offset-1
      table.table.table-striped.table-bordered
        thead
          th.text-center Наименование
          th.text-center Размер
          th.text-center Цена за ед.(руб.)
          th.text-center Количество
          th.text-center Стоимость(руб.)
        tbody
          - @order.line_items.each do |line_item|
            = render partial: 'order_row', locals: {line_item: line_item}
          tr
            td.text-right.bg-warning colspan='5'
              h4
                = "Общая стоимость - #{number_to_currency(@order.total_price, delimiter: ' ', precision: 0, format: '%n руб.')}"
          tr
            td colspan='5'
              .col-md-2.col-md-offset-8.text-right
                = link_to 'Отклонить', root_path, class: 'btn btn-warning text-right'
              .col-md-2
                = f.submit 'Подтвердить', class: 'btn btn-success text-right'

app/views/orders/index.html.slim
.row
  .col-md-8.col-md-offset-2
    table.table.table-striped.table-bordered
      thead
        td.text-center Дата
        td.text-center Общая стоимость(руб.)
        td.text-center Статус
        td
      tbody
        = render @orders

app/views/orders/show.html.slim
.row
  .col-md-10.col-md-offset-1
    table.table.table-striped.table-bordered
      thead
        th.text-center Наименование
        th.text-center Размер
        th.text-center Цена за ед.(руб.)
        th.text-center Количество
        th.text-center Стоимость(руб.)
      tbody
        - @order.line_items.each do |line_item|
          = render partial: 'order_row', locals: {line_item: line_item}
        tr
          td.text-right.bg-warning colspan='5'
            h4
              = "Общая стоимость - #{number_to_currency(@order.total_price, delimiter: ' ', precision: 0, format: '%n руб.')}"

app/views/products/_product.html.slim
tr
  td.align-middle.col-md-4
      = product.name
  td.col-md-2.text-center
    = ff.select :product_attr_id, product.sorted.map { |prod_attr| [prod_attr.size.value, prod_attr.id] }
  td.col-md-2
    ul.align-middle.ul-center
      - product.sorted.map(&:price).each_with_index do |price, idx|
        - if idx.zero?
          li
            = number_to_currency(price, delimiter: ' ', precision: 0, format: '%n')
        - else
          li.hidden
            = number_to_currency(price, delimiter: ' ', precision: 0, format: '%n')
  td.col-md-2
    ul.align-middle.ul-center
      - product.sorted.map(&:amount).each_with_index do |amount, idx|
        - if idx.zero?
          li
            = amount
        - else
          li.hidden
            = amount
  - if user_signed_in?
    td.col-md-2
      .col-xs-8
        = ff.text_field :quantity, class: 'text-center form-control input-sm'
      .col-xs-4 style="margin-top: 3px"
        span.glyphicon.glyphicon-remove.align-middle.pointer

app/views/products/index.html.slim
.row
  = form_for @order do |f|
    .col-md-10.col-md-offset-1
      - if user_signed_in?
        .col-md-3.col-md-offset-9
          = f.submit 'Оформить', class: 'btn btn-primary btn-block'
          br
      table.table.table-striped.table-bordered
        thead
          th.text-center Наименование
          th.text-center Размер
          th.text-center Цена за ед.(руб.)
          th.text-center Наличие
          - if user_signed_in?
            th.text-center Количество
        tbody
          - @products.each do |product|
            - line_item = LineItem.new
            = f.fields_for :line_items, line_item do |ff|
              = render partial: 'product', locals: {ff: ff, product: product}

app/views/profiles/edit.html.slim
.row
  .col-md-4.col-md-offset-4
    = form_for @user, url: profile_path do |f|
      .form-group
        label Email
        = f.text_field :email, class: 'form-control', placeholder: 'example@example.com'
      .form-group
        label Организация
        = f.text_field :organization, class: 'form-control', placeholder: "ЧУП \"Иванов\""
      .form-group
        label
          | Мобильный номер
        .input-group
          .input-group-addon
            | +375
          = f.text_field :phone_number, class: 'form-control', placeholder: '291234321'
      .form-group
        label
          | Новый пароль
          em
            = " (8 #{@minimum_password_length} символов минимум)"
        = f.password_field :password, class: 'form-control', autocomplete: 'off', placeholder: 'Пароль'
      .form-group
        label
          | Подтверждение пароля
        = f.password_field :password_confirmation, class: 'form-control', autocomplete: 'off', placeholder: 'Подтверждение пароля'
      .form-group
        = f.submit 'Обновить', class: 'btn btn-info'